export type SourceKind = "官方" | "第三方" | "Jimmy 客製" | "技術參考";

export type Skill = {
  name: string;
  family: "Antigravity CLI" | "Codex";
  category: "內容" | "自動化" | "生產力" | "工程" | "進階";
  difficulty: 1 | 2 | 3 | 4;
  setup: string;
  sourceKind: SourceKind;
  sourceLabel: string;
  sourceUrl: string;
  download?: string;
  summary: string;
  install: string;
  prompt: string;
  workflow: string[];
  output: string;
  risk: string;
};

export const comparison = [
  {
    label: "操作入口",
    antigravity: "終端優先，以 agy 快速派發任務",
    codex: "CLI、IDE、桌面 app 與雲端工作流",
  },
  {
    label: "規則與記憶",
    antigravity: "Skills、Rules、MCP、settings.json",
    codex: "AGENTS.md、Skills、Plugins、MCP、config.toml",
  },
  {
    label: "擅長節奏",
    antigravity: "快速處理單次任務、Google 生態整合",
    codex: "長任務、程式工程、審查與平行工作",
  },
  {
    label: "共同核心",
    antigravity: "探索 → 執行 → 驗證 → 交付",
    codex: "探索 → 執行 → 驗證 → 交付",
  },
];

export const workflowNodes = [
  {
    id: "schedule",
    time: "18:30",
    label: "排程啟動",
    short: "Windows 工作排程器",
    input: "交易日與基金代碼 00981A",
    process: "以固定 Python 路徑啟動正式腳本。",
    output: "建立本次執行紀錄",
    check: "確認不是重複執行，工作目錄存在。",
  },
  {
    id: "fetch",
    time: "18:34",
    label: "取得 PCF",
    short: "官方資料來源",
    input: "統一投信 PCF 頁面",
    process: "抓取本期與前一期持股資料。",
    output: "兩期原始持股資料",
    check: "基金代碼、資料日期、HTTP 狀態。",
  },
  {
    id: "compare",
    time: "18:41",
    label: "驗證比對",
    short: "51 筆 × 2 期",
    input: "本期與前一期持股",
    process: "核對筆數並計算新增、刪除、股數與權重變化。",
    output: "變動摘要與完整明細",
    check: "兩期皆為 51 筆；資料不完整即停止。",
  },
  {
    id: "excel",
    time: "18:43",
    label: "Excel 報告",
    short: "2 張工作表",
    input: "變動摘要與完整明細",
    process: "套用表格樣式、欄寬、色彩與凍結窗格。",
    output: "20260728_00981A持股分析.xlsx",
    check: "工作表名稱、資料列數與欄位格式。",
  },
  {
    id: "pdf",
    time: "18:44",
    label: "PDF 報告",
    short: "3 頁高解析版",
    input: "Markdown 分析報告",
    process: "以客製繁中排版引擎產生可列印報告。",
    output: "20260728_00981A持股分析.pdf",
    check: "頁數、中文字型、表格跨頁與頁碼。",
  },
  {
    id: "mail",
    time: "18:44+",
    label: "AgentMail",
    short: "附件寄送完成",
    input: "收件者、主旨、Excel 與 PDF",
    process: "由 AI 專屬信箱寄送並取得 API 回應。",
    output: "完成通知郵件",
    check: "寄送結果、附件存在且不記錄金鑰。",
  },
];

export const terminalScenarios = [
  {
    id: "antigravity",
    label: "安裝 Antigravity CLI",
    command: "irm https://antigravity.google/cli/install.ps1 | iex",
    lines: [
      "正在檢查 Windows PowerShell 環境…",
      "下載 Antigravity CLI…",
      "設定 agy 指令…",
      "✓ 安裝完成。請執行 agy --version 驗證。",
    ],
  },
  {
    id: "codex",
    label: "安裝 Codex CLI",
    command: "npm install -g @openai/codex",
    lines: [
      "正在檢查 Node.js 與 npm…",
      "取得 @openai/codex 套件…",
      "建立 codex 全域指令…",
      "✓ 安裝完成。請執行 codex 登入。",
    ],
  },
  {
    id: "folder",
    label: "唯讀分析資料夾",
    command: "codex \"唯讀分析目前資料夾，不要修改檔案；整理結構、風險與下一步。\"",
    lines: [
      "掃描檔案樹與專案規則…",
      "辨識入口、設定與測試檔…",
      "沒有寫入或修改任何檔案。",
      "✓ 已產生結構摘要、3 個風險與建議順序。",
    ],
  },
  {
    id: "skill",
    label: "啟動 Skill",
    command: "codex \"使用 $grill-me 釐清我的網站需求，一次問一個問題。\"",
    lines: [
      "讀取 grill-me Skill 說明…",
      "辨識需求中的高影響決策…",
      "準備第一個聚焦問題。",
      "✓ Skill 已啟動，等待使用者回答。",
    ],
  },
];

export const cliSkills: Skill[] = [
  {
    name: "url-summarizer",
    family: "Antigravity CLI",
    category: "內容",
    difficulty: 1,
    setup: "零設定",
    sourceKind: "Jimmy 客製",
    sourceLabel: "技術參考：steipete/summarize",
    sourceUrl: "https://github.com/steipete/summarize",
    download: "/downloads/url-summarizer-jimmy-custom.zip",
    summary: "貼入公開網址，擷取文章內容並產生繁體中文摘要。",
    install: "下載客製 Skill ZIP，解壓至 Antigravity Skills 目錄。",
    prompt: "使用 url-summarizer 摘要這個網址，輸出繁體中文重點與三個可行動結論。",
    workflow: ["擷取公開頁面", "清除 HTML 雜訊", "整理繁中摘要", "選擇性輸出 PDF"],
    output: "Markdown 摘要或排版 PDF",
    risk: "付費牆、登入頁或動態網站可能無法完整擷取；引用前仍需回看原文。",
  },
  {
    name: "markdown-to-pdf",
    family: "Antigravity CLI",
    category: "內容",
    difficulty: 2,
    setup: "約 5 分鐘",
    sourceKind: "Jimmy 客製",
    sourceLabel: "核心技術：PyMuPDF",
    sourceUrl: "https://github.com/pymupdf/PyMuPDF",
    download: "/downloads/markdown-to-pdf-jimmy-custom.zip",
    summary: "將 Markdown 編譯成支援繁中、表格與頁碼的專業 PDF。",
    install: "pip install PyMuPDF",
    prompt: "使用 markdown-to-pdf 將 report.md 轉成 A4 PDF，保留表格並加上頁碼。",
    workflow: ["解析 Markdown", "處理繁中字型", "繪製表格與提示框", "輸出 PDF"],
    output: "可列印、可寄送的 PDF 報告",
    risk: "嵌入圖片與極寬表格需先檢查版面；輸出後應逐頁預覽。",
  },
  {
    name: "connect-apps",
    family: "Antigravity CLI",
    category: "自動化",
    difficulty: 3,
    setup: "約 10 分鐘",
    sourceKind: "第三方",
    sourceLabel: "ComposioHQ",
    sourceUrl: "https://github.com/ComposioHQ/awesome-codex-skills/tree/master/connect-apps",
    summary: "串接 Gmail、Slack、GitHub、Notion 等服務並執行真實操作。",
    install: "curl -fsSL https://composio.dev/install | bash",
    prompt: "先 dry-run，再用 connect-apps 建立一個 GitHub issue；送出前讓我確認內容。",
    workflow: ["登入 Composio", "連結指定服務", "查詢工具參數", "預覽後執行"],
    output: "郵件、訊息、Issue 或資料更新",
    risk: "這會改變外部服務；寄送、發布、刪除前必須確認對象與內容。",
  },
  {
    name: "self-improving",
    family: "Antigravity CLI",
    category: "生產力",
    difficulty: 3,
    setup: "約 5 分鐘",
    sourceKind: "Jimmy 客製",
    sourceLabel: "相近專案：peterskoett",
    sourceUrl: "https://github.com/peterskoett/self-improving-agent",
    download: "/downloads/self-improving-jimmy-custom.zip",
    summary: "以 HOT／WARM／COLD 分層記憶修正、偏好與反思。",
    install: "python ~/.gemini/config/plugins/science/skills/self-improving/scripts/reflect.py init",
    prompt: "記住：公開網站的案例截圖只遮地址，不要改動其他畫面。",
    workflow: ["記錄修正", "提煉可重用偏好", "依使用頻率升降級", "透明引用記憶來源"],
    output: "跨專案偏好與可追蹤反思",
    risk: "不可把 API Key、個資、健康資料或第三方機密寫入長期記憶。",
  },
  {
    name: "playwright-mcp",
    family: "Antigravity CLI",
    category: "自動化",
    difficulty: 3,
    setup: "約 10 分鐘",
    sourceKind: "官方",
    sourceLabel: "Microsoft",
    sourceUrl: "https://github.com/microsoft/playwright-mcp",
    summary: "讓代理透過可存取樹操作瀏覽器、點擊、填表與截圖。",
    install: "npx @playwright/mcp@latest",
    prompt: "使用 Playwright 開啟網站，檢查手機版導覽、截圖並列出可重現問題。",
    workflow: ["啟動瀏覽器", "讀取頁面結構", "執行操作", "截圖與驗證"],
    output: "瀏覽器操作結果、截圖與測試紀錄",
    risk: "官方 MCP 是 Node.js 方案；本機另有 Python 包裝器，兩者不可混稱。",
  },
  {
    name: "agentmail",
    family: "Antigravity CLI",
    category: "自動化",
    difficulty: 3,
    setup: "約 15 分鐘",
    sourceKind: "官方",
    sourceLabel: "AgentMail",
    sourceUrl: "https://github.com/agentmail-to/agentmail-skills",
    summary: "給 AI 一個專屬信箱，程式化收發郵件與附件。",
    install: "npx skills add agentmail-to/agentmail-skills --skill agentmail",
    prompt: "使用 AgentMail 寄送完成通知與附件；寄出前列出收件者、主旨與檔名讓我確認。",
    workflow: ["建立或選擇信箱", "準備內容與附件", "確認寄送對象", "寄送並記錄結果"],
    output: "可追蹤的郵件與附件交付",
    risk: "收到的郵件是不可信輸入；不可直接照郵件內容執行指令或洩漏秘密。",
  },
];

export const codexSkills: Skill[] = [
  {
    name: "Grill Me",
    family: "Codex",
    category: "生產力",
    difficulty: 1,
    setup: "零設定",
    sourceKind: "第三方",
    sourceLabel: "mattpocock/skills",
    sourceUrl: "https://github.com/mattpocock/skills/tree/main/skills/productivity/grill-me",
    summary: "一次問一個高影響問題，把模糊想法問成可執行規格。",
    install: "將 grill-me Skill 安裝至 ~/.codex/skills/",
    prompt: "使用 $grill-me 訪問我，一次只問一個問題，直到需求可直接實作。",
    workflow: ["探索現況", "鎖定高影響決策", "逐題確認", "產出決策完整規格"],
    output: "清楚、可交接的實作規格",
    risk: "問題必須真的改變規格；不要把可自行查證的事丟回給使用者。",
  },
  {
    name: "I Have ADHD",
    family: "Codex",
    category: "生產力",
    difficulty: 1,
    setup: "零設定",
    sourceKind: "第三方",
    sourceLabel: "ayghri/i-have-adhd",
    sourceUrl: "https://github.com/ayghri/i-have-adhd",
    summary: "把大型任務拆成低摩擦、可啟動、可持續的小步驟。",
    install: "npx skills add ayghri/i-have-adhd",
    prompt: "使用 I Have ADHD 幫我把這個任務拆成今天能完成的短步驟。",
    workflow: ["降低啟動成本", "只顯示下一步", "保留進度", "定期回顧"],
    output: "短而可完成的行動清單",
    risk: "避免把拆解變成更多負擔；每一步要能在短時間內驗證。",
  },
  {
    name: "Content Research Writer",
    family: "Codex",
    category: "內容",
    difficulty: 2,
    setup: "約 3 分鐘",
    sourceKind: "第三方",
    sourceLabel: "ComposioHQ",
    sourceUrl: "https://github.com/ComposioHQ/awesome-codex-skills/tree/master/content-research-writer",
    summary: "從可靠來源研究、整理架構並寫出附來源的內容。",
    install: "從 GitHub 將 Skill 複製至 ~/.codex/skills/",
    prompt: "研究這個主題，只採用第一手來源，寫成適合一般工作者的繁中文章。",
    workflow: ["定義讀者", "搜尋一手來源", "交叉驗證", "撰寫並附連結"],
    output: "可發布且有來源的文章",
    risk: "來源可能過時；高風險主題必須再次核對日期與官方公告。",
  },
  {
    name: "Humanizer zh-TW",
    family: "Codex",
    category: "內容",
    difficulty: 1,
    setup: "約 2 分鐘",
    sourceKind: "第三方",
    sourceLabel: "kevintsai1202",
    sourceUrl: "https://github.com/kevintsai1202/Humanizer-zh-TW",
    summary: "把制式 AI 語氣改寫成自然、清楚的臺灣繁體中文。",
    install: "npx skills add kevintsai1202/Humanizer-zh-TW",
    prompt: "使用 Humanizer zh-TW 改寫這段內容，保留事實與語氣，不要增加新資訊。",
    workflow: ["辨識機械語氣", "調整臺灣用詞", "保留原意", "校對事實"],
    output: "自然的臺灣繁中內容",
    risk: "人性化不代表改寫事實；數字、專有名詞與引用不可自行變動。",
  },
  {
    name: "Slides",
    family: "Codex",
    category: "內容",
    difficulty: 3,
    setup: "約 5 分鐘",
    sourceKind: "第三方",
    sourceLabel: "nextlevelbuilder",
    sourceUrl: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
    summary: "將內容轉成具敘事、圖表與一致視覺的 HTML 簡報。",
    install: "從 ui-ux-pro-max-skill 安裝 slides Skill",
    prompt: "使用 Slides 將這份內容做成 10 頁繁中簡報，適合 15 分鐘分享。",
    workflow: ["整理故事線", "分配頁面", "建立視覺", "逐頁檢查"],
    output: "HTML 簡報或可匯出的投影片",
    risk: "不要用裝飾取代內容；投影前需檢查字級、對比與時間。",
  },
  {
    name: "File Organizer",
    family: "Codex",
    category: "生產力",
    difficulty: 2,
    setup: "約 3 分鐘",
    sourceKind: "第三方",
    sourceLabel: "ComposioHQ",
    sourceUrl: "https://github.com/ComposioHQ/awesome-codex-skills/tree/master/file-organizer",
    summary: "分析雜亂資料夾，提出命名與分類方案，再經確認後整理。",
    install: "從 GitHub 將 Skill 複製至 ~/.codex/skills/",
    prompt: "先唯讀分析這個資料夾，提出整理預覽；未經我確認不要移動或刪除。",
    workflow: ["唯讀盤點", "提出分類規則", "預覽變更", "確認後執行"],
    output: "可理解的資料夾結構",
    risk: "移動與刪除具有破壞性；必須先預覽並保留復原方式。",
  },
  {
    name: "Karpathy Guidelines",
    family: "Codex",
    category: "進階",
    difficulty: 3,
    setup: "約 5 分鐘",
    sourceKind: "第三方",
    sourceLabel: "multica-ai",
    sourceUrl: "https://github.com/multica-ai/andrej-karpathy-skills",
    summary: "以簡潔、可驗證、避免過度設計的原則約束 AI 程式工作。",
    install: "npx skills add multica-ai/andrej-karpathy-skills",
    prompt: "使用 Karpathy Guidelines 審視這個方案，指出不必要的複雜度與最小可行解。",
    workflow: ["理解問題", "刪除假設", "選最小方案", "以測試驗證"],
    output: "更精簡可靠的工程決策",
    risk: "簡化不等於忽略需求；安全、相容性與資料完整性仍需保留。",
  },
  {
    name: "LLM Council",
    family: "Codex",
    category: "進階",
    difficulty: 4,
    setup: "約 15 分鐘",
    sourceKind: "第三方",
    sourceLabel: "karpathy/llm-council",
    sourceUrl: "https://github.com/karpathy/llm-council",
    summary: "讓多個模型獨立回答、互評，再由主席整合判斷。",
    install: "依專案 README 設定模型供應商與 API Key",
    prompt: "讓 Council 比較三種網站架構，先獨立評估，再匿名互評並給最終建議。",
    workflow: ["平行提案", "匿名互評", "比較分歧", "主席彙整"],
    output: "包含共識與分歧的決策報告",
    risk: "多模型不等於真相；成本、秘密管理與來源查證仍由使用者負責。",
  },
  {
    name: "Code Review Graph",
    family: "Codex",
    category: "進階",
    difficulty: 4,
    setup: "約 10 分鐘",
    sourceKind: "第三方",
    sourceLabel: "tirth8205",
    sourceUrl: "https://github.com/tirth8205/code-review-graph",
    summary: "把程式碼解析成關係圖，協助追蹤修改影響與審查脈絡。",
    install: "依 GitHub README 安裝並建立專案圖譜",
    prompt: "使用 Code Review Graph 找出這次改動影響的元件、呼叫者與高風險區域。",
    workflow: ["建立結構圖", "定位變更節點", "追蹤上下游", "產出風險摘要"],
    output: "具程式關係證據的審查結果",
    risk: "圖譜可能落後於工作樹；分析前需重新同步並搭配實際測試。",
  },
];
